@baseUrl = http://localhost:3000

### Create post
POST {{baseUrl}}/post
Content-Type: application/json

{
  "message": "First post",
  "sender": "student1"
}

### Get all posts
GET {{baseUrl}}/post

### Get posts by sender
GET {{baseUrl}}/post?sender=student1

### Get post by id
GET {{baseUrl}}/post/<postId>

### Update post
PUT {{baseUrl}}/post/<postId>
Content-Type: application/json

{
  "message": "Updated post",
  "sender": "student1"
}


### --------------------------------------------------------------
### 6. CREATE A COMMENT (Linked to Post from Step 1)
### --------------------------------------------------------------
# @name createComment
POST {{baseUrl}}/comments
Content-Type: application/json

{
    "postId": "{{postId}}",
    "sender": "JaneSmith",
    "content": "This is a comment on the automated post."
}

### --------------------------------------------------------------
### 7. GET COMMENTS FOR THIS POST
### --------------------------------------------------------------
GET {{baseUrl}}/comments/post/{{postId}}

### --------------------------------------------------------------
### 8. UPDATE THE COMMENT (Using ID from Step 6)
### --------------------------------------------------------------
@commentId = {{createComment.response.body._id}}

PUT {{baseUrl}}/comments/{{commentId}}
Content-Type: application/json

{
    "content": "I have updated my comment!"
}

### --------------------------------------------------------------
### 9. DELETE THE COMMENT
### --------------------------------------------------------------
DELETE {{baseUrl}}/comments/{{commentId}}
```